<?php
/**
 * Implements hook_form_FORM_ID_alter()
   Sort the list of values for a exposed filter in a view
   $form_state['view']->filter               : contains all filters within the view
   $filter->options['expose']['identifier']  : gets the filter identifier used on $form
   $form[$fid]['#options']                   : list all the values of the filter
 */
function yahook_form_views_exposed_form_alter(&$form, $form_state) {
    foreach($form_state['view']->filter as $filter) {
        if($fid = $filter->options['expose']['identifier']) asort($form[$fid]['#options']);
    }
}

